# Generated by Django 4.2.7 on 2024-05-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppChat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
