# Generated by Django 5.2.7 on 2026-09-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppChat', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AddField(
            model_name='users',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
