# Generated by Django 4.2.7 on 2024-05-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLoginAndRegister', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
